#!/usr/bin/python3
#coding=utf-8
#单进程运行


from telnetlib import Telnet
import time

def tftp_put(ip, cp, tftp):
	try:
		tn = Telnet(ip, 23)
		time.sleep(1)
		tn.write(b'root\n') #b是将字符串转换为bytes（字节）类型的数据，常用于网络数据传输、二进制图片和文件的保存等等。
		time.sleep(1)
		tn.write(b'cd /com/etc/usr\n')
		time.sleep(1)
		tn.write(b'sync\n')
		time.sleep(1)
		tn.write(cp.encode())
		time.sleep(1)
		tn.write(tftp.encode())
		time.sleep(2)
		tn.write(b'exit\n')
		tn.close()	
	except Exception as err:
		time.sleep(5)
		print(ID + str(err))
numbers = list(range(1,39,1))
for num in numbers:
	if num < 33:
		ip = "10.1.2." + str(num)
		cp = 'cp ZebOS.conf jr' + str(num) + '_ZebOS.conf' + '\n'
		tftp = 'tftp -pl jr' + str(num) + '_ZebOS.conf 10.1.77.77' + '\n'
	elif num < 35:
		ip = "10.1.3." + str(num - 32)
		cp = 'cp ZebOS.conf wg' + str(num - 32) + '_ZebOS.conf' + '\n'
		tftp = 'tftp -pl wg' + str(num - 32) + '_ZebOS.conf 10.1.77.77' + '\n'
	else:
		ip = "10.1.1." + str((num - 34) * 10)
		cp = 'cp ZebOS.conf hx' + str(num - 34) + '_ZebOS.conf' + '\n'
		tftp = 'tftp -pl hx' + str(num - 34) + '_ZebOS.conf 10.1.77.77' + '\n'
	tftp_put(ip, cp, tftp)

